name: ShareIt CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ShareIt  # Явное указание рабочей директории

    steps:
      - uses: actions/checkout@v4
        with:
          path: ShareIt  # Четкое определение пути

      - name: Validate structure
        run: |
          pwd
          ls -la
          ls -la shareit-gateway/
          ls -la shareit-server/

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -DskipTests