name: ShareIt API Tests

on:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'ShareIt'  # Явно указываем путь к проекту

      - name: Verify project structure
        run: |
          cd ShareIt
          ls -la
          ls -la shareit-gateway
          ls -la shareit-server

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd ShareIt
          mvn package -DskipTests

      - name: Start Spring Boot apps
        run: |
          cd ShareIt/shareit-server
          nohup java -jar target/shareit-server-1.0-SNAPSHOT.jar &
          cd ../shareit-gateway
          nohup java -jar target/shareit-gateway-1.0-SNAPSHOT.jar &
          
          echo "Waiting for apps to start..."
          timeout 120 bash -c 'while ! curl -s http://localhost:8080/actuator/health >/dev/null; do sleep 1; done'
          timeout 120 bash -c 'while ! curl -s http://localhost:9090/actuator/health >/dev/null; do sleep 1; done'

      - name: Run API tests
        run: |
          cd ShareIt
          mvn test