name: ShareIt API Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
    # Поднимаем H2 в памяти (не требует отдельного сервиса)

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -P check

      - name: Start application
        run: |
          java -jar target/later-spring-boot-1.0-SNAPSHOT.jar &
          sleep 15  # Даем приложению время на запуск

      - name: Wait for application
        run: |
          timeout 60 bash -c 'until curl -s http://localhost:8080/actuator/health >/dev/null; do sleep 2; done' || (echo "Application failed to start"; exit 1)

      - name: Run API tests
        run: |
          # Здесь могут быть ваши тесты
          curl -X GET "http://localhost:8080/items" -H "accept: application/json"

      - name: Verify logs
        if: always()
        run: |
          cat logs/shareit.log || echo "No log file found"