name: ShareIt CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история репозитория

      - name: Fix potential case issues
        run: |
          # Принудительно приводим к строчным буквам
          [ -d "ShareIt" ] && mv "ShareIt" "shareit" || true
          [ -d "shareIt" ] && mv "shareIt" "shareit" || true

      - name: Validate structure
        run: |
          echo "Working directory: $(pwd)"
          ls -la
          echo "Checking modules..."
          ls -la shareit-gateway/pom.xml shareit-server/pom.xml
          [ -f "shareit-gateway/pom.xml" ] || exit 1
          [ -f "shareit-server/pom.xml" ] || exit 1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -DskipTests