name: ShareIt API Tests

on:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'shareit-root'  # Явное указание корня проекта

      - name: Verify project structure
        run: |
          cd shareit-root
          ls -la
          echo "Checking modules..."
          ls -la shareit-gateway/pom.xml
          ls -la shareit-server/pom.xml
          echo "Structure verified."

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd shareit-root
          mvn clean package -DskipTests -B -e -X
          echo "Build completed"

      - name: Start services
        run: |
          cd shareit-root/shareit-server
          nohup java -jar target/shareit-server-*.jar &
          cd ../shareit-gateway
          nohup java -jar target/shareit-gateway-*.jar &
          
          echo "Waiting for services to start..."
          sleep 15
          curl -v http://localhost:8080/actuator/health
          curl -v http://localhost:9090/actuator/health

      - name: Run tests
        run: |
          cd shareit-root
          mvn test -B