name: ShareIt API Tests

on:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полный history репозитория

      - name: Debug structure
        run: |
          echo "Full structure:"
          find . -type d
          echo "Checking modules:"
          ls -la shareit-gateway/
          ls -la shareit-server/

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          echo "Current dir: $(pwd)"
          mvn clean package -DskipTests -B -e -X